### ISSUE TITLE
[BUG] going to world `defib:void` crashes the game

### ISSUE THREAD

**Issue by 456dev** [P03W/Defibrillator#3]
**Describe the bug**
switching to the defib:void world crashes the game

**To Reproduce**
1. create a new world with cheats
2. execute the command `/execute in defib:void run tp 0 100 0`
4. Experience crash in server

**Expected behavior**
the game not crashing, possibly just dening entry to the world

**Screenshots**
![image](https://user-images.githubusercontent.com/42748092/128219937-879361db-f784-401e-8a87-6384e6b5a86d.png)
![image](https://user-images.githubusercontent.com/42748092/128219798-8b7944ad-dc1a-40e8-9e73-af5c9f1cd9a1.png)

**Game and Mod version**
	- defibrillator@1.5.1
	- fabric@0.37.1+1.17
	- fabricloader@0.11.6
	- java@16
	- minecraft@1.17.1
	- mixintrace@1.1.0+1.17
	- modmenu@2.0.4
	- notenoughcrashes@3.4.0+1.17

**Game log and other mods**
[crash-2021-08-04_17.36.12-server.txt](https://github.com/P03W/Defibrillator/files/6932943/crash-2021-08-04_17.36.12-server.txt)
[latest.log](https://github.com/P03W/Defibrillator/files/6932944/latest.log)

**Comment by SilverAndro** [comment]
This dimension is still WIP and not meant for normal use, the crash will be fixed once the functionality is in place
